baseURL = 'https://hacker65536.github.io/o11y-2022-awscost-handson/'
languageCode = 'en-us'
title = 'o11y 2022 aws cost hands on'
theme = "hugo-theme-learn"


[params]
themeVariant = "blue"
editURL = "https://github.com/hacker65536/o11y-2022-awscost-handson/edit/main/content/"
